### ISSUE TITLE
gcc Error: wrong number of template arguments (1, should be 3)

### ISSUE THREAD

**Issue by vincent-t** [decimad/luabind-deboostified#27] opened 2016-11-06 13:02 UTC
```
out_value_policy.hpp:199:33: error: wrong number of template arguments (1, should be 3)
    storage_.template construct<T>();
out_value_policy.hpp:220:33: error: wrong number of template arguments (1, should be 3)
    storage_.template construct<T>();
```

**Comment by decimad** [comment] 2016-11-23 16:45
Hello, can you please provide a testcase or some sample code for me to look at?

**Comment by neomantra** [comment] 2017-02-17 21:49
I'm getting this on Ubuntu 16.04 with gcc 5.4.0, latest master:

```
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LUABIND=ON .
make
```

```
[ 79%] Building CXX object test/CMakeFiles/test_policies.dir/test_policies.cpp.o
In file included from /home/pc/evan/projects/luabind-deboostified/test/test_policies.cpp:26:0:
/home/pc/evan/projects/luabind-deboostified/luabind/out_value_policy.hpp: In member function ‘T& luabind::detail::pure_out_value_converter<Size, Policies>::to_cpp(lua_State*, luabind::detail::by_reference<T>, int)’:
/home/pc/evan/projects/luabind-deboostified/luabind/out_value_policy.hpp:200:34: error: wrong number of template arguments (1, should be 3)
     storage_.template construct<T>();
                                  ^
In file included from /home/pc/evan/projects/luabind-deboostified/luabind/class.hpp:83:0,
                 from /home/pc/evan/projects/luabind-deboostified/luabind/luabind.hpp:28,
                 from /home/pc/evan/projects/luabind-deboostified/test/test_policies.cpp:25:
/home/pc/evan/projects/luabind-deboostified/luabind/detail/constructor.hpp:51:10: note: provided for ‘template<class T, class Pointer, class Signature> struct luabind::detail::construct’
   struct construct :
          ^
In file included from /home/pc/evan/projects/luabind-deboostified/test/test_policies.cpp:26:0:
/home/pc/evan/projects/luabind-deboostified/luabind/out_value_policy.hpp: In member function ‘T* luabind::detail::pure_out_value_converter<Size, Policies>::to_cpp(lua_State*, luabind::detail::by_pointer<T>, int)’:
/home/pc/evan/projects/luabind-deboostified/luabind/out_value_policy.hpp:221:34: error: wrong number of template arguments (1, should be 3)
     storage_.template construct<T>();
                                  ^
In file included from /home/pc/evan/projects/luabind-deboostified/luabind/class.hpp:83:0,
                 from /home/pc/evan/projects/luabind-deboostified/luabind/luabind.hpp:28,
                 from /home/pc/evan/projects/luabind-deboostified/test/test_policies.cpp:25:
/home/pc/evan/projects/luabind-deboostified/luabind/detail/constructor.hpp:51:10: note: provided for ‘template<class T, class Pointer, class Signature> struct luabind::detail::construct’
   struct construct :
          ^
test/CMakeFiles/test_policies.dir/build.make:62: recipe for target 'test/CMakeFiles/test_policies.dir/test_policies.cpp.o' failed
make[2]: *** [test/CMakeFiles/test_policies.dir/test_policies.cpp.o] Error 1
CMakeFiles/Makefile2:2458: recipe for target 'test/CMakeFiles/test_policies.dir/all' failed
make[1]: *** [test/CMakeFiles/test_policies.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by neomantra** [comment] 2017-02-19 06:53
The Dockerfile below reproduces it on current master.  Save it as `Dockerfile.ubuntu` and build it like so:
```
cd luabind-deboostified
docker build -f Dockerfile.ubuntu .
```

```
# Dockerfile.ubuntu
FROM ubuntu:16.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \ 
        g++ \
        gcc \
        git \
        lua5.1-dev \
        make

RUN cd /tmp \
    && git clone https://github.com/decimad/luabind-deboostified.git

VOLUME  /tmp/luabind-deboostified

RUN cd /tmp/luabind-deboostified \
    && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -LUABIND_BUILD_SHARED=ON . \
    && make
```

**Comment by decimad** [comment] 2017-02-19 13:17
Hello, thank you for the feedback, I will see what I can do shortly.

**Comment by neomantra** [comment] 2017-02-19 14:05
I did further exploration last night.... using `ubuntu:16.10` and `gcc-6` elicits the same compiler error.   But, compiling on `ubuntu:16.10` and `clang` works (with a minor fix I had to do which I'll make a PR for later today).  I also tried C++14 standard with the same results.

I don't get why gcc is trying to use `luabind::detail::construct` instead of `out_value_detail::temporary_storage_size<Size>::contrust`

**Comment by neomantra** [comment] 2017-02-19 14:51
So as I was saying... if I rename `out_value_detail::temporary_storage_size<Size>::construct` to `construct2` and invoke that in lines 200 and 221, then it compiles fine.

I don't think there is a proper test for this (because commenting out the line entirely still passes the test), but it is compiling.

**Comment by decimad** [comment] 2017-05-06 20:51
Man, I don't understand this problem. It smells like a compiler bug really?

**Comment by decimad** [comment] 2017-05-06 20:56
Oh and out_value_converter is missing the dependant template keywords as well...

**Comment by decimad** [comment] 2017-07-06 21:14
I commited a preliminary fix as suggested on https://www.c-plusplus.net/forum/343641 that works without renaming.

All this line does is default-constructing an object in the already reserved memory. Since an "int" holds no invariants that could be broken, it is not important that the reference returned doesn't point to memory that was properly initialized by the out_value_policy. That's why the test still passes if you comment out that line.

**Comment by Wohlstand** [comment] 2017-07-07 11:23
I'll try to build that at me

**Comment by Wohlstand** [comment] 2017-07-07 11:36
Okay, you also forgot to apply fix at 221'th line where I did fix myself, but another issue has been found: 

impicit_cast test fails:
```
Running tests...
Test project /home/wohlstand/_git_repos/luabind-deboostified/build
      Start  1: abstract_base
 1/46 Test  #1: abstract_base ....................   Passed    0.01 sec
      Start  2: adopt
 2/46 Test  #2: adopt ............................   Passed    0.01 sec
      Start  3: adopt_wrapper
 3/46 Test  #3: adopt_wrapper ....................   Passed    0.00 sec
      Start  4: attributes
 4/46 Test  #4: attributes .......................   Passed    0.01 sec
      Start  5: automatic_smart_ptr
 5/46 Test  #5: automatic_smart_ptr ..............   Passed    0.01 sec
      Start  6: back_reference
 6/46 Test  #6: back_reference ...................   Passed    0.01 sec
      Start  7: builtin_converters
 7/46 Test  #7: builtin_converters ...............   Passed    0.00 sec
      Start  8: class_info
 8/46 Test  #8: class_info .......................   Passed    0.00 sec
      Start  9: collapse_converter
 9/46 Test  #9: collapse_converter ...............   Passed    0.00 sec
      Start 10: const
10/46 Test #10: const ............................   Passed    0.00 sec
      Start 11: construction
11/46 Test #11: construction .....................   Passed    0.00 sec
      Start 12: create_in_thread
12/46 Test #12: create_in_thread .................   Passed    0.00 sec
      Start 13: def_from_base
13/46 Test #13: def_from_base ....................   Passed    0.00 sec
      Start 14: dynamic_type
14/46 Test #14: dynamic_type .....................   Passed    0.00 sec
      Start 15: exception_handlers
15/46 Test #15: exception_handlers ...............   Passed    0.00 sec
      Start 16: exceptions
16/46 Test #16: exceptions .......................   Passed    0.00 sec
      Start 17: extend_class_in_lua
17/46 Test #17: extend_class_in_lua ..............   Passed    0.00 sec
      Start 18: free_functions
18/46 Test #18: free_functions ...................   Passed    0.00 sec
      Start 19: function_introspection
19/46 Test #19: function_introspection ...........   Passed    0.00 sec
      Start 20: held_type
20/46 Test #20: held_type ........................   Passed    0.00 sec
      Start 21: implicit_cast
21/46 Test #21: implicit_cast ....................***Failed    0.00 sec
      Start 22: implicit_raw
22/46 Test #22: implicit_raw .....................   Passed    0.00 sec
      Start 23: iterator
23/46 Test #23: iterator .........................   Passed    0.00 sec
      Start 24: lua_classes
24/46 Test #24: lua_classes ......................   Passed    0.00 sec
      Start 25: null_pointer
25/46 Test #25: null_pointer .....................   Passed    0.00 sec
      Start 26: object
26/46 Test #26: object ...........................   Passed    0.00 sec
      Start 27: operators
27/46 Test #27: operators ........................   Passed    0.00 sec
      Start 28: package_preload
28/46 Test #28: package_preload ..................   Passed    0.00 sec
      Start 29: policies
29/46 Test #29: policies .........................   Passed    0.00 sec
      Start 30: private_destructors
30/46 Test #30: private_destructors ..............   Passed    0.00 sec
      Start 31: properties
31/46 Test #31: properties .......................   Passed    0.00 sec
      Start 32: scope
32/46 Test #32: scope ............................   Passed    0.00 sec
      Start 33: separation
33/46 Test #33: separation .......................   Passed    0.00 sec
      Start 34: set_instance_value
34/46 Test #34: set_instance_value ...............   Passed    0.00 sec
      Start 35: shadow
35/46 Test #35: shadow ...........................   Passed    0.00 sec
      Start 36: shared_ptr
36/46 Test #36: shared_ptr .......................   Passed    0.00 sec
      Start 37: simple_class
37/46 Test #37: simple_class .....................   Passed    0.00 sec
      Start 38: smart_ptr_attributes
38/46 Test #38: smart_ptr_attributes .............   Passed    0.00 sec
      Start 39: super_leak
39/46 Test #39: super_leak .......................   Passed    0.00 sec
      Start 40: table
40/46 Test #40: table ............................   Passed    0.00 sec
      Start 41: tag_function
41/46 Test #41: tag_function .....................   Passed    0.00 sec
      Start 42: unsigned_int
42/46 Test #42: unsigned_int .....................   Passed    0.00 sec
      Start 43: user_defined_converter
43/46 Test #43: user_defined_converter ...........   Passed    0.00 sec
      Start 44: vector_of_object
44/46 Test #44: vector_of_object .................   Passed    0.00 sec
      Start 45: virtual_inheritance
45/46 Test #45: virtual_inheritance ..............   Passed    0.00 sec
      Start 46: yield
46/46 Test #46: yield ............................   Passed    0.00 sec

98% tests passed, 1 tests failed out of 46

Total Test time (real) =   0.11 sec

The following tests FAILED:
	 21 - implicit_cast (Failed)
Errors while running CTest
```

**Comment by decimad** [comment] 2017-07-07 15:47
Arrrr, I need to catch some sleep...
Btw.: This problem is/was actually a bug in gcc and clang.

**Comment by decimad** [comment] 2017-07-08 11:07
Okay, I think I can consider this fixed now, right?

**Closed by decimad** 2017-07-08 11:07 UTC
